keywords:
  - "夢ノ結唱"
  - "梦的结唱"
  - "Syntheiszer ROSE"
  - "Synthesizer POPY"
  - "Synthesizer PASTEL"
  - "Synthesizer HALO"
  - "ksm"
  - "ykn"
  - "kkr"
  - "香澄"
  - "友希那"
  - "丸山彩"
  - "弦卷心"
name: 梦的结唱8
time_start: "2025-09-27"
time_end: "2025-11-27"
video_zone_type: 0
